import type { Product, ProductVariant } from '@/types/database';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'eco-mailer-box',
    name: 'Eco Mailer Box',
    description: 'Sustainable corrugated mailer box perfect for e-commerce shipping. Made from 100% recycled materials with FSC certification.',
    category: 'mailer',
    base_price: 0.85,
    material_types: ['kraft', 'white'],
    minimum_order_quantity: 10,
    sample_price: 15.00,
    is_active: true,
    hero_image_url: '/images/products/eco-mailer.jpg',
    gallery_images: [
      '/images/products/eco-mailer.jpg',
      '/images/products/eco-mailer-2.jpg',
      '/images/products/eco-mailer-3.jpg',
    ],
    features: ['100% Recyclable', 'FSC Certified', 'Custom Print Ready', 'Easy Assembly'],
    eco_certified: true,
    lead_time_days: 14,
    setup_fee: 50.00,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    slug: 'premium-shipping-box',
    name: 'Premium Shipping Box',
    description: 'Heavy-duty shipping box with double-wall construction for maximum protection during transit.',
    category: 'shipping',
    base_price: 1.20,
    material_types: ['kraft', 'white', 'bleached'],
    minimum_order_quantity: 10,
    sample_price: 15.00,
    is_active: true,
    hero_image_url: '/images/products/shipping-box.jpg',
    gallery_images: ['/images/products/shipping-box.jpg'],
    features: ['Double Wall', 'Impact Resistant', 'Custom Sizes', 'Stackable'],
    eco_certified: true,
    lead_time_days: 12,
    setup_fee: 45.00,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    slug: 'luxury-rigid-box',
    name: 'Luxury Rigid Box',
    description: 'Premium rigid box with magnetic closure, ideal for luxury products, electronics, and gift packaging.',
    category: 'rigid',
    base_price: 3.50,
    material_types: ['white', 'bleached'],
    minimum_order_quantity: 30,
    sample_price: 25.00,
    is_active: true,
    hero_image_url: '/images/products/rigid-box.jpg',
    gallery_images: ['/images/products/rigid-box.jpg'],
    features: ['Magnetic Closure', 'Premium Feel', 'Foil Stamping Ready', 'Velvet Interior Option'],
    eco_certified: false,
    lead_time_days: 21,
    setup_fee: 120.00,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    slug: 'custom-paper-bag',
    name: 'Custom Paper Bag',
    description: 'Eco-friendly custom paper bags with twisted rope or ribbon handles for retail stores.',
    category: 'bags',
    base_price: 0.65,
    material_types: ['kraft', 'white'],
    minimum_order_quantity: 50,
    sample_price: 12.00,
    is_active: true,
    hero_image_url: '/images/products/paper-bag.jpg',
    gallery_images: ['/images/products/paper-bag.jpg'],
    features: ['Twisted Rope Handles', 'Full Color Print', 'Water-Based Inks', 'Reinforced Bottom'],
    eco_certified: true,
    lead_time_days: 10,
    setup_fee: 35.00,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    slug: 'product-box',
    name: 'Product Box',
    description: 'Versatile product packaging box perfect for cosmetics, food, and consumer goods.',
    category: 'mailer',
    base_price: 0.95,
    material_types: ['kraft', 'white', 'bleached'],
    minimum_order_quantity: 20,
    sample_price: 15.00,
    is_active: true,
    hero_image_url: '/images/products/product-box.jpg',
    gallery_images: ['/images/products/product-box.jpg'],
    features: ['Tuck End Design', 'Food Safe Option', 'Custom Windows', 'Embossing Ready'],
    eco_certified: true,
    lead_time_days: 14,
    setup_fee: 55.00,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    slug: 'poly-mailer',
    name: 'Poly Mailer Bag',
    description: 'Lightweight waterproof poly mailer for clothing and soft goods shipping.',
    category: 'bags',
    base_price: 0.35,
    material_types: ['white'],
    minimum_order_quantity: 100,
    sample_price: 10.00,
    is_active: true,
    hero_image_url: '/images/products/poly-mailer.jpg',
    gallery_images: ['/images/products/poly-mailer.jpg'],
    features: ['Waterproof', 'Tear Resistant', 'Self-Seal Strip', 'Lightweight'],
    eco_certified: false,
    lead_time_days: 7,
    setup_fee: 25.00,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

export const PRODUCT_VARIANTS: Record<string, ProductVariant[]> = {
  'eco-mailer-box': [
    {
      id: 'v1',
      product_id: '1',
      sku: 'EMB-S-KR',
      name: 'F44 - Small Kraft (200x150x80mm)',
      min_length_mm: 100, max_length_mm: 400,
      min_width_mm: 80, max_width_mm: 300,
      min_depth_mm: 30, max_depth_mm: 200,
      preset_length_mm: 200, preset_width_mm: 150, preset_depth_mm: 80,
      material_type: 'kraft', material_thickness_gsm: 300,
      material_cost_per_sqm: 2.20,
      finish_options: ['matte', 'glossy'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'v2',
      product_id: '1',
      sku: 'EMB-M-KR',
      name: 'F45 - Medium Kraft (300x220x100mm)',
      min_length_mm: 150, max_length_mm: 500,
      min_width_mm: 100, max_width_mm: 400,
      min_depth_mm: 40, max_depth_mm: 250,
      preset_length_mm: 300, preset_width_mm: 220, preset_depth_mm: 100,
      material_type: 'kraft', material_thickness_gsm: 350,
      material_cost_per_sqm: 2.50,
      finish_options: ['matte', 'glossy', 'foil'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'v3',
      product_id: '1',
      sku: 'EMB-L-KR',
      name: 'F46 - Large Kraft (400x300x150mm)',
      min_length_mm: 200, max_length_mm: 600,
      min_width_mm: 150, max_width_mm: 500,
      min_depth_mm: 50, max_depth_mm: 300,
      preset_length_mm: 400, preset_width_mm: 300, preset_depth_mm: 150,
      material_type: 'kraft', material_thickness_gsm: 400,
      material_cost_per_sqm: 2.80,
      finish_options: ['matte', 'glossy', 'foil', 'spot_uv'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'v4',
      product_id: '1',
      sku: 'EMB-S-WH',
      name: 'F44 - Small White (200x150x80mm)',
      min_length_mm: 100, max_length_mm: 400,
      min_width_mm: 80, max_width_mm: 300,
      min_depth_mm: 30, max_depth_mm: 200,
      preset_length_mm: 200, preset_width_mm: 150, preset_depth_mm: 80,
      material_type: 'white', material_thickness_gsm: 300,
      material_cost_per_sqm: 2.60,
      finish_options: ['matte', 'glossy', 'foil'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'v5',
      product_id: '1',
      sku: 'EMB-M-WH',
      name: 'F45 - Medium White (300x220x100mm)',
      min_length_mm: 150, max_length_mm: 500,
      min_width_mm: 100, max_width_mm: 400,
      min_depth_mm: 40, max_depth_mm: 250,
      preset_length_mm: 300, preset_width_mm: 220, preset_depth_mm: 100,
      material_type: 'white', material_thickness_gsm: 350,
      material_cost_per_sqm: 2.90,
      finish_options: ['matte', 'glossy', 'foil', 'spot_uv'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  'premium-shipping-box': [
    {
      id: 'v6',
      product_id: '2',
      sku: 'PSB-S-KR',
      name: 'S1 - Small Kraft (250x200x100mm)',
      min_length_mm: 150, max_length_mm: 500,
      min_width_mm: 100, max_width_mm: 400,
      min_depth_mm: 50, max_depth_mm: 300,
      preset_length_mm: 250, preset_width_mm: 200, preset_depth_mm: 100,
      material_type: 'kraft', material_thickness_gsm: 450,
      material_cost_per_sqm: 3.00,
      finish_options: ['matte'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'v7',
      product_id: '2',
      sku: 'PSB-M-KR',
      name: 'S2 - Medium Kraft (350x280x150mm)',
      min_length_mm: 200, max_length_mm: 600,
      min_width_mm: 150, max_width_mm: 500,
      min_depth_mm: 80, max_depth_mm: 400,
      preset_length_mm: 350, preset_width_mm: 280, preset_depth_mm: 150,
      material_type: 'kraft', material_thickness_gsm: 500,
      material_cost_per_sqm: 3.40,
      finish_options: ['matte', 'glossy'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'v8',
      product_id: '2',
      sku: 'PSB-L-WH',
      name: 'S3 - Large White (450x350x200mm)',
      min_length_mm: 250, max_length_mm: 700,
      min_width_mm: 200, max_width_mm: 600,
      min_depth_mm: 100, max_depth_mm: 500,
      preset_length_mm: 450, preset_width_mm: 350, preset_depth_mm: 200,
      material_type: 'white', material_thickness_gsm: 500,
      material_cost_per_sqm: 3.80,
      finish_options: ['matte', 'glossy', 'foil'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  'luxury-rigid-box': [
    {
      id: 'v9',
      product_id: '3',
      sku: 'LRB-S-WH',
      name: 'R1 - Small White Rigid (150x120x60mm)',
      min_length_mm: 100, max_length_mm: 300,
      min_width_mm: 80, max_width_mm: 250,
      min_depth_mm: 40, max_depth_mm: 150,
      preset_length_mm: 150, preset_width_mm: 120, preset_depth_mm: 60,
      material_type: 'white', material_thickness_gsm: 1200,
      material_cost_per_sqm: 8.50,
      finish_options: ['matte', 'glossy', 'foil', 'spot_uv', 'embossed'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'v10',
      product_id: '3',
      sku: 'LRB-M-BL',
      name: 'R2 - Medium Bleached Rigid (250x180x100mm)',
      min_length_mm: 150, max_length_mm: 400,
      min_width_mm: 100, max_width_mm: 350,
      min_depth_mm: 50, max_depth_mm: 200,
      preset_length_mm: 250, preset_width_mm: 180, preset_depth_mm: 100,
      material_type: 'bleached', material_thickness_gsm: 1400,
      material_cost_per_sqm: 10.20,
      finish_options: ['matte', 'glossy', 'foil', 'spot_uv', 'embossed'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  'custom-paper-bag': [
    {
      id: 'v11',
      product_id: '4',
      sku: 'CPB-S-KR',
      name: 'B1 - Small Kraft Bag (180x80x60mm)',
      min_length_mm: 100, max_length_mm: 300,
      min_width_mm: 60, max_width_mm: 200,
      min_depth_mm: 30, max_depth_mm: 150,
      preset_length_mm: 180, preset_width_mm: 80, preset_depth_mm: 60,
      material_type: 'kraft', material_thickness_gsm: 150,
      material_cost_per_sqm: 1.80,
      finish_options: ['matte', 'glossy'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'v12',
      product_id: '4',
      sku: 'CPB-M-WH',
      name: 'B2 - Medium White Bag (260x120x80mm)',
      min_length_mm: 150, max_length_mm: 400,
      min_width_mm: 80, max_width_mm: 300,
      min_depth_mm: 40, max_depth_mm: 200,
      preset_length_mm: 260, preset_width_mm: 120, preset_depth_mm: 80,
      material_type: 'white', material_thickness_gsm: 170,
      material_cost_per_sqm: 2.20,
      finish_options: ['matte', 'glossy', 'foil'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  'product-box': [
    {
      id: 'v13',
      product_id: '5',
      sku: 'PB-S-KR',
      name: 'P1 - Small Kraft Product Box (150x100x50mm)',
      min_length_mm: 80, max_length_mm: 300,
      min_width_mm: 60, max_width_mm: 250,
      min_depth_mm: 30, max_depth_mm: 150,
      preset_length_mm: 150, preset_width_mm: 100, preset_depth_mm: 50,
      material_type: 'kraft', material_thickness_gsm: 350,
      material_cost_per_sqm: 2.40,
      finish_options: ['matte', 'glossy'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'v14',
      product_id: '5',
      sku: 'PB-M-WH',
      name: 'P2 - Medium White Product Box (220x160x80mm)',
      min_length_mm: 100, max_length_mm: 400,
      min_width_mm: 80, max_width_mm: 350,
      min_depth_mm: 40, max_depth_mm: 200,
      preset_length_mm: 220, preset_width_mm: 160, preset_depth_mm: 80,
      material_type: 'white', material_thickness_gsm: 400,
      material_cost_per_sqm: 2.80,
      finish_options: ['matte', 'glossy', 'foil', 'spot_uv'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  'poly-mailer': [
    {
      id: 'v15',
      product_id: '6',
      sku: 'PM-S-WH',
      name: 'M1 - Small White Poly (250x200mm)',
      min_length_mm: 150, max_length_mm: 400,
      min_width_mm: 100, max_width_mm: 300,
      min_depth_mm: 0, max_depth_mm: 0,
      preset_length_mm: 250, preset_width_mm: 200, preset_depth_mm: 0,
      material_type: 'white', material_thickness_gsm: 60,
      material_cost_per_sqm: 0.80,
      finish_options: ['matte', 'glossy'],
      is_active: true,
      created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
    },
  ],
};

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getVariantsForProduct(slug: string): ProductVariant[] {
  return PRODUCT_VARIANTS[slug] || [];
}
